##
#  SimBase Configuration
##

defaults:
  server:
    ip: 0.0.0.0
    port: 7654
  engine:
    cronInterval: 7200000
    cloneThrottle: 1800000
    maxlimits: 20
    loadfactor: 0.75
    debug: true
    bycount: 100
  basis:
    vectorSetType: denseVectorSet
  denseVectorSet:
    accumuFactor: 0.01
    sparseFactor: 4096
  sparseVectorSet:
    accumuFactor: 0.01
    sparseFactor: 4096
